%% EventCatalog Mermaid Diagram
%% Resource: commands/modulith.application.arcadia-editions-modulith.startOrderCheckout (v0.0.1)
%% Generated: 2026-08-26T20:38:03.306Z

flowchart LR

    %% Style definitions
    classDef commands fill:#3b82f6,stroke:#1d4ed8,color:#fff

    %% Nodes
    modulith_application_arcadia_editions_modulith_startOrderCheckout_0_0_1>"startOrderCheckout (0.0.1)"]:::commands

    %% Edges