%% EventCatalog Mermaid Diagram
%% Resource: events/notifications.customer-communications.notifications-consumer.order-cancelled-notification-sent-event-v1 (v0.1.0)
%% Generated: 2026-08-26T20:38:03.221Z

flowchart LR

    %% Style definitions
    classDef events fill:#f97316,stroke:#c2410c,color:#fff
    classDef services fill:#ec4899,stroke:#be185d,color:#fff
    classDef channels fill:#6b7280,stroke:#374151,color:#fff

    %% Nodes
    notifications_customer_communications_notifications_consumer_order_cancelled_notification_sent_event_v1_0_1_0>"order-cancelled-notification-sent-event-v1 (0.1.0)"]:::events
    notifications_customer_communications_notifications_consumer_0_1_0[["Notifications Consumer (0.1.0)"]]:::services
    notifications_customer_communications_notifications_consumer_order_cancelled_notification_sent_event_v1_0_1_0[("order-cancelled-notification-sent-event-v1 (0.1.0)")]:::channels

    %% Edges
    notifications_customer_communications_notifications_consumer_0_1_0 -->|"publishes  event"| notifications_customer_communications_notifications_consumer_order_cancelled_notification_sent_event_v1_0_1_0
    notifications_customer_communications_notifications_consumer_order_cancelled_notification_sent_event_v1_0_1_0 -->|"routes to"| notifications_customer_communications_notifications_consumer_order_cancelled_notification_sent_event_v1_0_1_0