%% EventCatalog Mermaid Diagram
%% Resource: events/fulfillment.shipping.fulfillment-shipping.fulfillment-failed-event-v1 (v0.0.1)
%% Generated: 2026-08-03T19:48:10.990Z

flowchart LR

    %% Style definitions
    classDef events fill:#f97316,stroke:#c2410c,color:#fff
    classDef services fill:#ec4899,stroke:#be185d,color:#fff
    classDef channels fill:#6b7280,stroke:#374151,color:#fff

    %% Nodes
    fulfillment_shipping_fulfillment_shipping_fulfillment_failed_event_v1_0_0_1>"fulfillment-failed-event-v1 (0.0.1)"]:::events
    fulfillment_shipping_fulfillment_shipping_0_0_1[["Fulfillment Shipping (0.0.1)"]]:::services
    fulfillment_shipping_fulfillment_shipping_fulfillment_failed_event_v1_0_0_1[("fulfillment-failed-event-v1 (0.0.1)")]:::channels

    %% Edges
    fulfillment_shipping_fulfillment_shipping_0_0_1 -->|"publishes  event"| fulfillment_shipping_fulfillment_shipping_fulfillment_failed_event_v1_0_0_1
    fulfillment_shipping_fulfillment_shipping_fulfillment_failed_event_v1_0_0_1 -->|"routes to"| fulfillment_shipping_fulfillment_shipping_fulfillment_failed_event_v1_0_0_1