%% EventCatalog Mermaid Diagram
%% Resource: events/payments.payment-processing.payments-processing.payment-failed-event-v1 (v0.1.0)
%% Generated: 2026-08-26T20:38:03.247Z

flowchart LR

    %% Style definitions
    classDef events fill:#f97316,stroke:#c2410c,color:#fff
    classDef services fill:#ec4899,stroke:#be185d,color:#fff
    classDef channels fill:#6b7280,stroke:#374151,color:#fff

    %% Nodes
    payments_payment_processing_payments_processing_payment_failed_event_v1_0_1_0>"payment-failed-event-v1 (0.1.0)"]:::events
    payments_payment_processing_payments_processing_0_1_0[["Payments Processing (0.1.0)"]]:::services
    payments_payment_processing_payments_processing_payment_failed_event_v1_0_1_0[("payment-failed-event-v1 (0.1.0)")]:::channels
    payments_payment_processing_payments_processing_0_1_0[["Payments Processing (0.1.0)"]]:::services
    payments_payment_processing_payments_processing_payment_failed_event_v1_0_1_0[("payment-failed-event-v1 (0.1.0)")]:::channels

    %% Edges
    payments_payment_processing_payments_processing_0_1_0 -->|"publishes  event"| payments_payment_processing_payments_processing_payment_failed_event_v1_0_1_0
    payments_payment_processing_payments_processing_payment_failed_event_v1_0_1_0 -->|"routes to"| payments_payment_processing_payments_processing_payment_failed_event_v1_0_1_0
    payments_payment_processing_payments_processing_payment_failed_event_v1_0_1_0 -->|"routes to"| payments_payment_processing_payments_processing_payment_failed_event_v1_0_1_0
    payments_payment_processing_payments_processing_payment_failed_event_v1_0_1_0 -->|"consumes"| payments_payment_processing_payments_processing_0_1_0
    payments_payment_processing_payments_processing_payment_failed_event_v1_0_1_0 -->|"publishes and subscribes"| payments_payment_processing_payments_processing_0_1_0