%% EventCatalog Mermaid Diagram
%% Resource: commands/orders.checkout.orders-checkout.startOrderCheckout (v0.1.0)
%% Generated: 2026-08-26T20:38:03.308Z

flowchart LR

    %% Style definitions
    classDef commands fill:#3b82f6,stroke:#1d4ed8,color:#fff

    %% Nodes
    orders_checkout_orders_checkout_startOrderCheckout_0_1_0>"startOrderCheckout (0.1.0)"]:::commands

    %% Edges