%% EventCatalog Mermaid Diagram
%% Resource: events/fulfillment.shipping.fulfillment-shipping.fulfillment-ready-to-ship-event-v1 (v0.1.0)
%% Generated: 2026-08-26T20:38:03.208Z

flowchart LR

    %% Style definitions
    classDef events fill:#f97316,stroke:#c2410c,color:#fff
    classDef services fill:#ec4899,stroke:#be185d,color:#fff
    classDef channels fill:#6b7280,stroke:#374151,color:#fff

    %% Nodes
    fulfillment_shipping_fulfillment_shipping_fulfillment_ready_to_ship_event_v1_0_1_0>"fulfillment-ready-to-ship-event-v1 (0.1.0)"]:::events
    fulfillment_shipping_fulfillment_shipping_0_1_0[["Fulfillment Shipping (0.1.0)"]]:::services
    fulfillment_shipping_fulfillment_shipping_fulfillment_ready_to_ship_event_v1_0_1_0[("fulfillment-ready-to-ship-event-v1 (0.1.0)")]:::channels

    %% Edges
    fulfillment_shipping_fulfillment_shipping_0_1_0 -->|"publishes  event"| fulfillment_shipping_fulfillment_shipping_fulfillment_ready_to_ship_event_v1_0_1_0
    fulfillment_shipping_fulfillment_shipping_fulfillment_ready_to_ship_event_v1_0_1_0 -->|"routes to"| fulfillment_shipping_fulfillment_shipping_fulfillment_ready_to_ship_event_v1_0_1_0