%% EventCatalog Mermaid Diagram
%% Resource: events/catalog.catalog-management.catalog-products.product-published-event-v1 (v0.5.0)
%% Generated: 2026-08-26T20:38:03.259Z

flowchart LR

    %% Style definitions
    classDef events fill:#f97316,stroke:#c2410c,color:#fff
    classDef services fill:#ec4899,stroke:#be185d,color:#fff
    classDef channels fill:#6b7280,stroke:#374151,color:#fff

    %% Nodes
    catalog_catalog_management_catalog_products_product_published_event_v1_0_5_0>"product-published-event-v1 (0.5.0)"]:::events
    catalog_catalog_management_catalog_products_0_5_0[["Catalog Products (0.5.0)"]]:::services
    catalog_catalog_management_catalog_products_product_published_event_v1_0_5_0[("product-published-event-v1 (0.5.0)")]:::channels

    %% Edges
    catalog_catalog_management_catalog_products_0_5_0 -->|"publishes  event"| catalog_catalog_management_catalog_products_product_published_event_v1_0_5_0
    catalog_catalog_management_catalog_products_product_published_event_v1_0_5_0 -->|"routes to"| catalog_catalog_management_catalog_products_product_published_event_v1_0_5_0