%% EventCatalog Mermaid Diagram
%% Resource: services/fulfillment.shipping.fulfillment-shipping (v0.0.0)
%% Generated: 2026-08-26T20:38:03.328Z

flowchart LR

    %% Style definitions
    classDef services fill:#ec4899,stroke:#be185d,color:#fff

    %% Nodes
    fulfillment_shipping_fulfillment_shipping_0_0_0[["Fulfillment Shipping (0.0.0)"]]:::services

    %% Edges