%% EventCatalog Mermaid Diagram
%% Resource: services/payments.payment-processing.payments-processing (v0.0.0)
%% Generated: 2026-08-26T20:38:03.364Z

flowchart LR

    %% Style definitions
    classDef services fill:#ec4899,stroke:#be185d,color:#fff

    %% Nodes
    payments_payment_processing_payments_processing_0_0_0[["Payments Processing (0.0.0)"]]:::services

    %% Edges