%% EventCatalog Mermaid Diagram
%% Resource: services/orders.checkout.orders-checkout (v0.0.0)
%% Generated: 2026-08-26T20:38:03.351Z

flowchart LR

    %% Style definitions
    classDef services fill:#ec4899,stroke:#be185d,color:#fff

    %% Nodes
    orders_checkout_orders_checkout_0_0_0[["Orders Checkout (0.0.0)"]]:::services

    %% Edges