%% EventCatalog Mermaid Diagram
%% Resource: commands/catalog.inventory-management.catalog-inventory.adjustStock (v0.1.0)
%% Generated: 2026-08-26T20:38:03.285Z

flowchart LR

    %% Style definitions
    classDef commands fill:#3b82f6,stroke:#1d4ed8,color:#fff

    %% Nodes
    catalog_inventory_management_catalog_inventory_adjustStock_0_1_0>"adjustStock (0.1.0)"]:::commands

    %% Edges