%% EventCatalog Mermaid Diagram
%% Resource: commands/catalog.catalog-management.catalog-products.createProduct (v0.1.0)
%% Generated: 2026-08-26T20:38:03.289Z

flowchart LR

    %% Style definitions
    classDef commands fill:#3b82f6,stroke:#1d4ed8,color:#fff

    %% Nodes
    catalog_catalog_management_catalog_products_createProduct_0_1_0>"createProduct (0.1.0)"]:::commands

    %% Edges