%% EventCatalog Mermaid Diagram
%% Resource: domains/payments (v0.0.1)
%% Generated: 2026-08-03T19:48:11.165Z

flowchart LR

    %% Style definitions
    classDef events fill:#f97316,stroke:#c2410c,color:#fff
    classDef services fill:#ec4899,stroke:#be185d,color:#fff

    %% Nodes
    payments_payment_processing_payments_processing_payment_failed_event_v1_0_0_1>"payment-failed-event-v1 (0.0.1)"]:::events
    payments_payment_processing_payments_processing_0_0_1[["Payments Processing (0.0.1)"]]:::services
    payments_payment_processing_payments_processing_payment_capture_failed_event_v1_0_0_1>"payment-capture-failed-event-v1 (0.0.1)"]:::events
    payments_payment_processing_payments_processing_payment_authorized_event_v1_0_0_1>"payment-authorized-event-v1 (0.0.1)"]:::events
    payments_payment_processing_payments_processing_payment_declined_event_v1_0_0_1>"payment-declined-event-v1 (0.0.1)"]:::events
    payments_payment_processing_payments_processing_payment_retried_event_v1_0_0_1>"payment-retried-event-v1 (0.0.1)"]:::events
    payments_payment_processing_payments_processing_payment_retry_exhausted_event_v1_0_0_1>"payment-retry-exhausted-event-v1 (0.0.1)"]:::events
    payments_payment_processing_payments_processing_payment_captured_event_v1_0_0_1>"payment-captured-event-v1 (0.0.1)"]:::events
    payments_payment_processing_payments_processing_payment_voided_event_v1_0_0_1>"payment-voided-event-v1 (0.0.1)"]:::events

    %% Edges
    payments_payment_processing_payments_processing_payment_failed_event_v1_0_0_1 -->|"subscribed by"| payments_payment_processing_payments_processing_0_0_1
    payments_payment_processing_payments_processing_0_0_1 -->|"publishes  event"| payments_payment_processing_payments_processing_payment_failed_event_v1_0_0_1
    payments_payment_processing_payments_processing_payment_failed_event_v1_0_0_1 -->|"routes to"| payments_payment_processing_payments_processing_payment_failed_event_v1_0_0_1
    payments_payment_processing_payments_processing_payment_capture_failed_event_v1_0_0_1 -->|"subscribed by"| payments_payment_processing_payments_processing_0_0_1
    payments_payment_processing_payments_processing_0_0_1 -->|"publishes  event"| payments_payment_processing_payments_processing_payment_capture_failed_event_v1_0_0_1
    payments_payment_processing_payments_processing_payment_capture_failed_event_v1_0_0_1 -->|"routes to"| payments_payment_processing_payments_processing_payment_capture_failed_event_v1_0_0_1
    payments_payment_processing_payments_processing_0_0_1 -->|"publishes  event"| payments_payment_processing_payments_processing_payment_authorized_event_v1_0_0_1
    payments_payment_processing_payments_processing_payment_authorized_event_v1_0_0_1 -->|"routes to"| payments_payment_processing_payments_processing_payment_authorized_event_v1_0_0_1
    payments_payment_processing_payments_processing_0_0_1 -->|"publishes  event"| payments_payment_processing_payments_processing_payment_declined_event_v1_0_0_1
    payments_payment_processing_payments_processing_payment_declined_event_v1_0_0_1 -->|"routes to"| payments_payment_processing_payments_processing_payment_declined_event_v1_0_0_1
    payments_payment_processing_payments_processing_0_0_1 -->|"publishes  event"| payments_payment_processing_payments_processing_payment_retried_event_v1_0_0_1
    payments_payment_processing_payments_processing_payment_retried_event_v1_0_0_1 -->|"routes to"| payments_payment_processing_payments_processing_payment_retried_event_v1_0_0_1
    payments_payment_processing_payments_processing_0_0_1 -->|"publishes  event"| payments_payment_processing_payments_processing_payment_retry_exhausted_event_v1_0_0_1
    payments_payment_processing_payments_processing_payment_retry_exhausted_event_v1_0_0_1 -->|"routes to"| payments_payment_processing_payments_processing_payment_retry_exhausted_event_v1_0_0_1
    payments_payment_processing_payments_processing_0_0_1 -->|"publishes  event"| payments_payment_processing_payments_processing_payment_captured_event_v1_0_0_1
    payments_payment_processing_payments_processing_payment_captured_event_v1_0_0_1 -->|"routes to"| payments_payment_processing_payments_processing_payment_captured_event_v1_0_0_1
    payments_payment_processing_payments_processing_0_0_1 -->|"publishes  event"| payments_payment_processing_payments_processing_payment_voided_event_v1_0_0_1
    payments_payment_processing_payments_processing_payment_voided_event_v1_0_0_1 -->|"routes to"| payments_payment_processing_payments_processing_payment_voided_event_v1_0_0_1
    payments_payment_processing_payments_processing_0_0_1 -->|"publishes event & receives event"| payments_payment_processing_payments_processing_payment_failed_event_v1_0_0_1
    payments_payment_processing_payments_processing_0_0_1 -->|"publishes event & receives event"| payments_payment_processing_payments_processing_payment_capture_failed_event_v1_0_0_1