%% EventCatalog Mermaid Diagram
%% Resource: services/notifications.customer-communications.notifications-consumer (v0.0.0)
%% Generated: 2026-08-26T20:38:03.337Z

flowchart LR

    %% Style definitions
    classDef services fill:#ec4899,stroke:#be185d,color:#fff

    %% Nodes
    notifications_customer_communications_notifications_consumer_0_0_0[["Notifications Consumer (0.0.0)"]]:::services

    %% Edges