%% EventCatalog Mermaid Diagram
%% Resource: services/catalog.inventory-management.catalog-inventory (v0.0.0)
%% Generated: 2026-08-26T20:38:03.314Z

flowchart LR

    %% Style definitions
    classDef services fill:#ec4899,stroke:#be185d,color:#fff

    %% Nodes
    catalog_inventory_management_catalog_inventory_0_0_0[["Catalog Inventory (0.0.0)"]]:::services

    %% Edges