%% EventCatalog Mermaid Diagram
%% Resource: commands/catalog.inventory-management.catalog-inventory.createInventoryPosition (v0.1.0)
%% Generated: 2026-08-26T20:38:03.287Z

flowchart LR

    %% Style definitions
    classDef commands fill:#3b82f6,stroke:#1d4ed8,color:#fff

    %% Nodes
    catalog_inventory_management_catalog_inventory_createInventoryPosition_0_1_0>"createInventoryPosition (0.1.0)"]:::commands

    %% Edges