%% EventCatalog Mermaid Diagram
%% Resource: domains/modulith (v0.0.1)
%% Generated: 2026-08-26T20:38:03.442Z

flowchart LR

    %% Style definitions
    classDef services fill:#ec4899,stroke:#be185d,color:#fff

    %% Nodes
    modulith_application_arcadia_editions_modulith_0_0_1[["Arcadia Editions Modulith (0.0.1)"]]:::services

    %% Edges